config/routes.rb
Rails.application.routes.draw do
  resources :food_items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'contact_us' => 'welcome#contact_us'
  get 'menu' => 'welcome#menu'
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
	validates :name, :section, presence: true
end

app/models/section.rb
class Section
	def self.all
		%w(Breakfast Lunch Dinner Drinks)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :descripion, :price, :section, :image_url)
    end
end

app/controllers/welcome_controller.rb
 class WelcomeController < ApplicationController
	def index
	end

	def contact_us
	end

	def menu
		if params[:section]
			@food_items =  FoodItem.where section: params[:section]
		else
			@food_items = FoodItem.all
		end

	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/food_items/_form.html.erb
<%= form_for(food_item) do |f| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'form-control-label' %>
    <br>
    <%= f.text_field :name, clas: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :descripion, class: 'form-control-label' %><br>
    <%= f.text_area :descripion, clas: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price, class: 'form-control-label' %>
    <%= f.text_field :price, clas: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :section, class: 'form-control-label' %>
    <%= f.text_field :section, clas: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image_url, class: 'form-control-label' %> 
    <%= f.text_field :image_url, clas: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table class="table table-striped">
  <thead class='thead thead-default'>
    <tr>
      <th>Name</th>
      <th>Descripion</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.descripion %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><%= image_tag food_item.image_url %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path, clas: 'btn btn-secondary' %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Descripion:</strong>
  <%= @food_item.descripion %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Section:</strong>
  <%= @food_item.section %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @food_item.image_url %>
</p>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRestaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-faded">
    	<a class="navbar-brand" href="<%= root_path%>">MyRetaurant</a>
    	<ul class="nav navbar-nav">
            <li class="nav-item <%= 'active' if current_page?(root_path) %>">
                <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>

    		<li class="nav-item <%= 'active' if current_page?(menu_path) %>">
    			<a class="nav-link" href="<%= menu_path%>"">Menu<span class="sr-only">(current)</span></a>
    		</li>
    		<li class="nav-item <%= 'active' if current_page?(contact_us_path) %>">
    			<a class="nav-link" href="<%= contact_us_path%>"">Contact Us</a>
    		</li>
    	</ul>
    	<form class="form-inline pull-xs-right">
    		<input class="form-control" type="text" placeholder="Search">
    		<button class="btn btn-outline-success" type="submit">Search</button>
    	</form>
    </nav>
    <div class="container">
    	<%= yield %>
    </div>
    
  </body>
</html>

app/views/welcome/contact_us.html.erb
<div class='row'>
	<div class='col-xs-3'>
		<h4>My Restaurant</h4>
		<address>
			57/10 Nguyễn Thị Nhỏ
			phường 9
			Tân Bình
			Hồ Chí Minh
			Vietnam
			+84 123456789<br>
			Open: 7:30AM–10:30PM
		</address>
	</div>
	<div class='col-xs-9'>
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.552294277981!2d106.65009331427689!3d10.76894626227776!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752e95494f73c5%3A0x44a3d8350c50a475!2zNTcvMTAgTmd1eeG7hW4gVGjhu4sgTmjhu48sIHBoxrDhu51uZyA5LCBUw6JuIELDrG5oLCBI4buTIENow60gTWluaCwgVmlldG5hbQ!5e0!3m2!1sen!2s!4v1476613132780" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>	
</div>

app/views/welcome/index.html.erb
<p>
  <div class="jumbotron">
  <h1 class="display-3">Welcome to myRestaurant !</h1>
  <hr class="m-y-2">
  <p>Are you HUNGRY? Go to Menu page</p>
  <p class="lead">
    <%= link_to "Menu", menu_path ,class: "btn btn-primary btn-lg" %>
    <%= link_to "Constact Us", contact_us_path ,class: "btn btn-secondary btn-lg" %>
  </p>
</div>
</p>

app/views/welcome/menu.html.erb
<h1>Menu</h1>

<% Section.all.each do |section| %>
	<div class="btn-group" role="group" aria-label="Basic example"> 
	 	 <%= link_to section, menu_path(section: section), class: 'btn btn-secondary' %>
	</div>
<% end %>


	<% @food_items.each do |food_item| %>
		<div class="card">
				<div class="card-header"><%= food_item.name%></div>
		</div> 
		<div class="card-block">
			<div class="row">
				<div class="col-xs-12 col-md-8">
					<%= image_tag food_item.image_url %>
				</div>
				<div class="col-xs-6 col-md-4">
					<p><strong>Description:</strong> <%= food_item.descripion %></p>
					<p><strong>Price:</strong> <%= food_item.price %> VND</p>
				</div>

			</div>
			
			
		</div>
	<% end %>